apiVersion: apps/v1
kind: Deployment
metadata:
  name: managedcluster-admission
  labels:
    app: managedcluster-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managedcluster-admission
  template:
    metadata:
      labels:
        app: managedcluster-admission
    spec:
      serviceAccountName: managedcluster-admission-sa
      containers:
      - name: managedcluster-admission
        image: quay.io/open-cluster-management/registration:latest
        imagePullPolicy: Always
        args:
          - "/registration"
          - "webhook"
          - "--secure-port=6443"
          - --tls-cert-file=/var/run/managedcluster-admission/tls.crt
          - --tls-private-key-file=/var/run/managedcluster-admission/tls.key
          # webhook is not hosting any k8s api resource, so it is not subjected to APF feature
          - "--feature-gates=DefaultClusterSet=true,APIPriorityAndFairness=false"
        volumeMounts:
          - mountPath: /var/run/managedcluster-admission
            name: webhook-cert
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
      volumes:
        - name: webhook-cert
          secret:
            defaultMode: 420
            secretName: managedcluster-admission