apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-manager-registration-webhook
  name: cluster-manager-registration-webhook
  namespace: open-cluster-management-hub
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: cluster-manager-registration-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cluster-manager-registration-webhook
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cluster-manager-registration-webhook
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cluster-manager-registration-webhook
              topologyKey: kubernetes.io/hostname
            weight: 30
      containers:
      - args:
        - /registration
        - "webhook-server"
        - "port=9443"
        image: quay.io/ldpliu/registration:96
        imagePullPolicy: Always
        name: webhook
        resources:
          requests:
            cpu: 2m
            memory: 16Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
        ports:
        - containerPort: 9443
          name: webhook-service
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: cluster-manager-registration-webhook-sa
      serviceAccountName: cluster-manager-registration-webhook-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-secret
        secret:
          defaultMode: 420
          secretName: registration-webhook-serving-cert
