apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook
  namespace: open-cluster-management-hub
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: webhook-service
  selector:
    app: cluster-manager-registration-webhook
